# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x07\n\x05\x45mpty\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x07\x42ooking\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x14\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x05.Date\"$\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t2\x85\x01\n\x08\x42ookings\x12#\n\x0bGetBookings\x12\x06.Empty\x1a\x08.Booking\"\x00\x30\x01\x12(\n\x11GetBookingForUser\x12\x07.UserID\x1a\x08.Booking\"\x00\x12*\n\x11\x41\x64\x64\x42ookingForUser\x12\x08.Booking\x1a\t.Response\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_USERID = DESCRIPTOR.message_types_by_name['UserID']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_BOOKING = DESCRIPTOR.message_types_by_name['Booking']
_DATE = DESCRIPTOR.message_types_by_name['Date']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

UserID = _reflection.GeneratedProtocolMessageType('UserID', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:UserID)
  })
_sym_db.RegisterMessage(UserID)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Booking = _reflection.GeneratedProtocolMessageType('Booking', (_message.Message,), {
  'DESCRIPTOR' : _BOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:Booking)
  })
_sym_db.RegisterMessage(Booking)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

_BOOKINGS = DESCRIPTOR.services_by_name['Bookings']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=17
  _EMPTY._serialized_end=24
  _USERID._serialized_start=26
  _USERID._serialized_end=46
  _RESPONSE._serialized_start=48
  _RESPONSE._serialized_end=75
  _BOOKING._serialized_start=77
  _BOOKING._serialized_end=124
  _DATE._serialized_start=126
  _DATE._serialized_end=162
  _BOOKINGS._serialized_start=165
  _BOOKINGS._serialized_end=298
# @@protoc_insertion_point(module_scope)
