# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x08\n\x06\x62\x45mpty\"\x15\n\x07\x62UserID\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\tbResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"1\n\x08\x62\x42ooking\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x15\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x06.bDate\"%\n\x05\x62\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t2\x8b\x01\n\x08\x42ookings\x12%\n\x0bGetBookings\x12\x07.bEmpty\x1a\t.bBooking\"\x00\x30\x01\x12*\n\x11GetBookingForUser\x12\x08.bUserID\x1a\t.bBooking\"\x00\x12,\n\x11\x41\x64\x64\x42ookingForUser\x12\t.bBooking\x1a\n.bResponse\"\x00\x62\x06proto3')



_BEMPTY = DESCRIPTOR.message_types_by_name['bEmpty']
_BUSERID = DESCRIPTOR.message_types_by_name['bUserID']
_BRESPONSE = DESCRIPTOR.message_types_by_name['bResponse']
_BBOOKING = DESCRIPTOR.message_types_by_name['bBooking']
_BDATE = DESCRIPTOR.message_types_by_name['bDate']
bEmpty = _reflection.GeneratedProtocolMessageType('bEmpty', (_message.Message,), {
  'DESCRIPTOR' : _BEMPTY,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:bEmpty)
  })
_sym_db.RegisterMessage(bEmpty)

bUserID = _reflection.GeneratedProtocolMessageType('bUserID', (_message.Message,), {
  'DESCRIPTOR' : _BUSERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:bUserID)
  })
_sym_db.RegisterMessage(bUserID)

bResponse = _reflection.GeneratedProtocolMessageType('bResponse', (_message.Message,), {
  'DESCRIPTOR' : _BRESPONSE,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:bResponse)
  })
_sym_db.RegisterMessage(bResponse)

bBooking = _reflection.GeneratedProtocolMessageType('bBooking', (_message.Message,), {
  'DESCRIPTOR' : _BBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:bBooking)
  })
_sym_db.RegisterMessage(bBooking)

bDate = _reflection.GeneratedProtocolMessageType('bDate', (_message.Message,), {
  'DESCRIPTOR' : _BDATE,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:bDate)
  })
_sym_db.RegisterMessage(bDate)

_BOOKINGS = DESCRIPTOR.services_by_name['Bookings']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BEMPTY._serialized_start=17
  _BEMPTY._serialized_end=25
  _BUSERID._serialized_start=27
  _BUSERID._serialized_end=48
  _BRESPONSE._serialized_start=50
  _BRESPONSE._serialized_end=78
  _BBOOKING._serialized_start=80
  _BBOOKING._serialized_end=129
  _BDATE._serialized_start=131
  _BDATE._serialized_end=168
  _BOOKINGS._serialized_start=171
  _BOOKINGS._serialized_end=310
# @@protoc_insertion_point(module_scope)
