# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\"E\n\x06mMovie\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x16\n\x08mMovieID\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\x0bmMovieTitle\x12\r\n\x05title\x18\x01 \x01(\t\"\x08\n\x06mEmpty\"\x1c\n\tmResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc8\x01\n\x06Movies\x12!\n\tGetMovies\x12\x07.mEmpty\x1a\x07.mMovie\"\x00\x30\x01\x12$\n\x0cGetMovieByID\x12\t.mMovieID\x1a\x07.mMovie\"\x00\x12*\n\x0fGetMovieByTitle\x12\x0c.mMovieTitle\x1a\x07.mMovie\"\x00\x12!\n\x08\x41\x64\x64Movie\x12\x07.mMovie\x1a\n.mResponse\"\x00\x12&\n\x0b\x44\x65leteMovie\x12\t.mMovieID\x1a\n.mResponse\"\x00\x62\x06proto3')



_MMOVIE = DESCRIPTOR.message_types_by_name['mMovie']
_MMOVIEID = DESCRIPTOR.message_types_by_name['mMovieID']
_MMOVIETITLE = DESCRIPTOR.message_types_by_name['mMovieTitle']
_MEMPTY = DESCRIPTOR.message_types_by_name['mEmpty']
_MRESPONSE = DESCRIPTOR.message_types_by_name['mResponse']
mMovie = _reflection.GeneratedProtocolMessageType('mMovie', (_message.Message,), {
  'DESCRIPTOR' : _MMOVIE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:mMovie)
  })
_sym_db.RegisterMessage(mMovie)

mMovieID = _reflection.GeneratedProtocolMessageType('mMovieID', (_message.Message,), {
  'DESCRIPTOR' : _MMOVIEID,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:mMovieID)
  })
_sym_db.RegisterMessage(mMovieID)

mMovieTitle = _reflection.GeneratedProtocolMessageType('mMovieTitle', (_message.Message,), {
  'DESCRIPTOR' : _MMOVIETITLE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:mMovieTitle)
  })
_sym_db.RegisterMessage(mMovieTitle)

mEmpty = _reflection.GeneratedProtocolMessageType('mEmpty', (_message.Message,), {
  'DESCRIPTOR' : _MEMPTY,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:mEmpty)
  })
_sym_db.RegisterMessage(mEmpty)

mResponse = _reflection.GeneratedProtocolMessageType('mResponse', (_message.Message,), {
  'DESCRIPTOR' : _MRESPONSE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:mResponse)
  })
_sym_db.RegisterMessage(mResponse)

_MOVIES = DESCRIPTOR.services_by_name['Movies']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MMOVIE._serialized_start=15
  _MMOVIE._serialized_end=84
  _MMOVIEID._serialized_start=86
  _MMOVIEID._serialized_end=108
  _MMOVIETITLE._serialized_start=110
  _MMOVIETITLE._serialized_end=138
  _MEMPTY._serialized_start=140
  _MEMPTY._serialized_end=148
  _MRESPONSE._serialized_start=150
  _MRESPONSE._serialized_end=178
  _MOVIES._serialized_start=181
  _MOVIES._serialized_end=381
# @@protoc_insertion_point(module_scope)
