# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"6\n\x05uUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0blast_active\x18\x03 \x01(\x05\"&\n\nuProtoUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x15\n\x07uUserID\x12\n\n\x02id\x18\x01 \x01(\t\"1\n\x08uBooking\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x15\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x06.uDate\"%\n\x05uDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"E\n\x06uMovie\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x1c\n\tuResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x08\n\x06uEmpty2\xc8\x01\n\x05Users\x12\x1f\n\x08GetUsers\x12\x07.uEmpty\x1a\x06.uUser\"\x00\x30\x01\x12!\n\x0bGetUserByID\x12\x08.uUserID\x1a\x06.uUser\"\x00\x12$\n\x07\x41\x64\x64User\x12\x0b.uProtoUser\x1a\n.uResponse\"\x00\x12*\n\x11GetBookingForUser\x12\x08.uUserID\x1a\t.uBooking\"\x00\x12)\n\x10GetMoviesForUser\x12\x08.uUserID\x1a\x07.uMovie\"\x00\x30\x01\x62\x06proto3')



_UUSER = DESCRIPTOR.message_types_by_name['uUser']
_UPROTOUSER = DESCRIPTOR.message_types_by_name['uProtoUser']
_UUSERID = DESCRIPTOR.message_types_by_name['uUserID']
_UBOOKING = DESCRIPTOR.message_types_by_name['uBooking']
_UDATE = DESCRIPTOR.message_types_by_name['uDate']
_UMOVIE = DESCRIPTOR.message_types_by_name['uMovie']
_URESPONSE = DESCRIPTOR.message_types_by_name['uResponse']
_UEMPTY = DESCRIPTOR.message_types_by_name['uEmpty']
uUser = _reflection.GeneratedProtocolMessageType('uUser', (_message.Message,), {
  'DESCRIPTOR' : _UUSER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:uUser)
  })
_sym_db.RegisterMessage(uUser)

uProtoUser = _reflection.GeneratedProtocolMessageType('uProtoUser', (_message.Message,), {
  'DESCRIPTOR' : _UPROTOUSER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:uProtoUser)
  })
_sym_db.RegisterMessage(uProtoUser)

uUserID = _reflection.GeneratedProtocolMessageType('uUserID', (_message.Message,), {
  'DESCRIPTOR' : _UUSERID,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:uUserID)
  })
_sym_db.RegisterMessage(uUserID)

uBooking = _reflection.GeneratedProtocolMessageType('uBooking', (_message.Message,), {
  'DESCRIPTOR' : _UBOOKING,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:uBooking)
  })
_sym_db.RegisterMessage(uBooking)

uDate = _reflection.GeneratedProtocolMessageType('uDate', (_message.Message,), {
  'DESCRIPTOR' : _UDATE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:uDate)
  })
_sym_db.RegisterMessage(uDate)

uMovie = _reflection.GeneratedProtocolMessageType('uMovie', (_message.Message,), {
  'DESCRIPTOR' : _UMOVIE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:uMovie)
  })
_sym_db.RegisterMessage(uMovie)

uResponse = _reflection.GeneratedProtocolMessageType('uResponse', (_message.Message,), {
  'DESCRIPTOR' : _URESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:uResponse)
  })
_sym_db.RegisterMessage(uResponse)

uEmpty = _reflection.GeneratedProtocolMessageType('uEmpty', (_message.Message,), {
  'DESCRIPTOR' : _UEMPTY,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:uEmpty)
  })
_sym_db.RegisterMessage(uEmpty)

_USERS = DESCRIPTOR.services_by_name['Users']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UUSER._serialized_start=14
  _UUSER._serialized_end=68
  _UPROTOUSER._serialized_start=70
  _UPROTOUSER._serialized_end=108
  _UUSERID._serialized_start=110
  _UUSERID._serialized_end=131
  _UBOOKING._serialized_start=133
  _UBOOKING._serialized_end=182
  _UDATE._serialized_start=184
  _UDATE._serialized_end=221
  _UMOVIE._serialized_start=223
  _UMOVIE._serialized_end=292
  _URESPONSE._serialized_start=294
  _URESPONSE._serialized_end=322
  _UEMPTY._serialized_start=324
  _UEMPTY._serialized_end=332
  _USERS._serialized_start=335
  _USERS._serialized_end=535
# @@protoc_insertion_point(module_scope)
