# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\"D\n\x05Movie\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x15\n\x07MovieID\x12\n\n\x02id\x18\x01 \x01(\t\"\x1b\n\nMovieTitle\x12\r\n\x05title\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbe\x01\n\x06Movies\x12\x1f\n\tGetMovies\x12\x06.Empty\x1a\x06.Movie\"\x00\x30\x01\x12\"\n\x0cGetMovieByID\x12\x08.MovieID\x1a\x06.Movie\"\x00\x12(\n\x0fGetMovieByTitle\x12\x0b.MovieTitle\x1a\x06.Movie\"\x00\x12\x1f\n\x08\x41\x64\x64Movie\x12\x06.Movie\x1a\t.Response\"\x00\x12$\n\x0b\x44\x65leteMovie\x12\x08.MovieID\x1a\t.Response\"\x00\x62\x06proto3')



_MOVIE = DESCRIPTOR.message_types_by_name['Movie']
_MOVIEID = DESCRIPTOR.message_types_by_name['MovieID']
_MOVIETITLE = DESCRIPTOR.message_types_by_name['MovieTitle']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), {
  'DESCRIPTOR' : _MOVIE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:Movie)
  })
_sym_db.RegisterMessage(Movie)

MovieID = _reflection.GeneratedProtocolMessageType('MovieID', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEID,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:MovieID)
  })
_sym_db.RegisterMessage(MovieID)

MovieTitle = _reflection.GeneratedProtocolMessageType('MovieTitle', (_message.Message,), {
  'DESCRIPTOR' : _MOVIETITLE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:MovieTitle)
  })
_sym_db.RegisterMessage(MovieTitle)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_MOVIES = DESCRIPTOR.services_by_name['Movies']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIE._serialized_start=15
  _MOVIE._serialized_end=83
  _MOVIEID._serialized_start=85
  _MOVIEID._serialized_end=106
  _MOVIETITLE._serialized_start=108
  _MOVIETITLE._serialized_end=135
  _EMPTY._serialized_start=137
  _EMPTY._serialized_end=144
  _RESPONSE._serialized_start=146
  _RESPONSE._serialized_end=173
  _MOVIES._serialized_start=176
  _MOVIES._serialized_end=366
# @@protoc_insertion_point(module_scope)
