# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"5\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0blast_active\x18\x03 \x01(\x05\"%\n\tProtoUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x07\x42ooking\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x14\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x05.Date\"$\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"D\n\x05Movie\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xbe\x01\n\x05Users\x12\x1d\n\x08GetUsers\x12\x06.Empty\x1a\x05.User\"\x00\x30\x01\x12\x1f\n\x0bGetUserByID\x12\x07.UserID\x1a\x05.User\"\x00\x12\"\n\x07\x41\x64\x64User\x12\n.ProtoUser\x1a\t.Response\"\x00\x12(\n\x11GetBookingForUser\x12\x07.UserID\x1a\x08.Booking\"\x00\x12\'\n\x10GetMoviesForUser\x12\x07.UserID\x1a\x06.Movie\"\x00\x30\x01\x62\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_PROTOUSER = DESCRIPTOR.message_types_by_name['ProtoUser']
_USERID = DESCRIPTOR.message_types_by_name['UserID']
_BOOKING = DESCRIPTOR.message_types_by_name['Booking']
_DATE = DESCRIPTOR.message_types_by_name['Date']
_MOVIE = DESCRIPTOR.message_types_by_name['Movie']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

ProtoUser = _reflection.GeneratedProtocolMessageType('ProtoUser', (_message.Message,), {
  'DESCRIPTOR' : _PROTOUSER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:ProtoUser)
  })
_sym_db.RegisterMessage(ProtoUser)

UserID = _reflection.GeneratedProtocolMessageType('UserID', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserID)
  })
_sym_db.RegisterMessage(UserID)

Booking = _reflection.GeneratedProtocolMessageType('Booking', (_message.Message,), {
  'DESCRIPTOR' : _BOOKING,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Booking)
  })
_sym_db.RegisterMessage(Booking)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), {
  'DESCRIPTOR' : _MOVIE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Movie)
  })
_sym_db.RegisterMessage(Movie)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_USERS = DESCRIPTOR.services_by_name['Users']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=14
  _USER._serialized_end=67
  _PROTOUSER._serialized_start=69
  _PROTOUSER._serialized_end=106
  _USERID._serialized_start=108
  _USERID._serialized_end=128
  _BOOKING._serialized_start=130
  _BOOKING._serialized_end=177
  _DATE._serialized_start=179
  _DATE._serialized_end=215
  _MOVIE._serialized_start=217
  _MOVIE._serialized_end=285
  _RESPONSE._serialized_start=287
  _RESPONSE._serialized_end=314
  _EMPTY._serialized_start=316
  _EMPTY._serialized_end=323
  _USERS._serialized_start=326
  _USERS._serialized_end=516
# @@protoc_insertion_point(module_scope)
