# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"(\n\x08Showtime\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x82\x01\n\tShowtimes\x12%\n\x0cGetShowtimes\x12\x06.Empty\x1a\t.Showtime\"\x00\x30\x01\x12\'\n\x11GetShowtimeByDate\x12\x05.Date\x1a\t.Showtime\"\x00\x12%\n\x0b\x41\x64\x64Showtime\x12\t.Showtime\x1a\t.Response\"\x00\x62\x06proto3')



_DATE = DESCRIPTOR.message_types_by_name['Date']
_SHOWTIME = DESCRIPTOR.message_types_by_name['Showtime']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

Showtime = _reflection.GeneratedProtocolMessageType('Showtime', (_message.Message,), {
  'DESCRIPTOR' : _SHOWTIME,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Showtime)
  })
_sym_db.RegisterMessage(Showtime)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_SHOWTIMES = DESCRIPTOR.services_by_name['Showtimes']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATE._serialized_start=18
  _DATE._serialized_end=38
  _SHOWTIME._serialized_start=40
  _SHOWTIME._serialized_end=80
  _RESPONSE._serialized_start=82
  _RESPONSE._serialized_end=109
  _EMPTY._serialized_start=111
  _EMPTY._serialized_end=118
  _SHOWTIMES._serialized_start=121
  _SHOWTIMES._serialized_end=251
# @@protoc_insertion_point(module_scope)
